<?php
return [
    'outputPath'=>'web/javascript/',

    'include'=>[
        'vendor/twbs/bootstrap/docs/assets/js/vendor'=>[
            'jquery.min.js',
            'tether.min.js',
        ],
        'vendor/twbs/bootstrap/docs/assets/js'=>[
            'ie10-viewport-bug-workaround.js',
        ],
        'vendor/twbs/bootstrap/dist/js'=>[
            'bootstrap.min.js',
        ],
        'vendor/stephanecollot/datetimepicker-bundle/SC/DatetimepickerBundle/Resources/public/js/'=>[
            'bootstrap-datetimepicker.js',
        ],
        'vendor/devlucid/lucid/src/js'=>[
            'lucid.js',
            'lucid.ruleset.js',
            'lucid.i18n.js',
            'lucid.dataTable.js',
            'lucid.messages.js',
        ],
        'vendor/devlucid/html/src/base/js'=>[
            'lucid.html.js',
            'lucid.html.dataTable.js',
        ],
        'app/javascript'=>[
            'app.js'
        ],
    ],
];