#!/usr/local/bin/php
<?php

namespace DevLucid;

$base_dir = __DIR__.'/../../../../';
include($base_dir.'bootstrap.php');

array_shift($argv);
if (count($argv) === 0) {
    printUsage();
}

$table = array_shift($argv);
$build['model'] = true;
$build['table'] = true;
$build['edit']  = true;
$build['controller'] = true;
$build['dictionary'] = true;

while (count($argv) > 0){
    $parameter = explode('=',array_shift($argv));
    if (isset($parameter[1]) === false || in_array($parameter[1], ['t','f','true','false']) === false || in_array($parameter[0], array_keys($build)) === false) {
        printUsage();
    }
    $build[$parameter[0]] = ($parameter[1] == 't' || $parameter[1] == 'true');
}

if ($table == 'all') {
    $meta = new Metabase(\ORM::get_db());
    $tables = $meta->getTables();
    foreach ($tables as $table) {
        perform_build($table, $build['model'], $build['table'], $build['edit'], $build['controller'], $build['dictionary']);
    }
} else {
    perform_build($table, $build['model'], $build['table'], $build['edit'], $build['controller'], $build['dictionary']);
}
exit("Complete\n");


function perform_build(string $table, bool $build_model = true, bool $build_table = true, bool $build_edit = true,  bool $build_controller = true, bool $build_dictionary = true)
{
    $always_exclude = ['phinxlog', 'sqlite_sequence'];

    if(in_array($table, $always_exclude) == true) {
        return;
    }

    echo("---------------------------------\n");
    echo ("Table: $table\n");
    $base_dir = __DIR__.'/../../../../';
    $meta = new Metabase(\ORM::get_db());

    if($meta->isTable($table, true) === false)
    {
        exit("$table is not a table or view in your database.");
    }

    $columns = $meta->getColumns($table);
    $template_keys = [
        'title'=>ucwords($table),
        'table'=>$table,
        'uc(table)'=>ucwords($table),
        'id'=>$columns[0]['name'],
        'save_actions'=>'',
        'rules'=>'',
        'form_fields'=>'',
        'save_parameters'=>'',
        'first_string_col'=>null,
        'table_cols'=>'',
        'search_cols'=>[],

        'select_options'=>'',

        'phpdoc_save_summary'=>'',
        'phpdoc_save_params'=>'',
    ];
    $dictionary = [];
    $dictionary['model:'.$table] = $table;

    # determine max length of a column, useful for formatting
    $longest = 0;
    for ($i=1; $i<count($columns); $i++) {
        if (strlen($columns[$i]['name']) > $longest) {
            $longest = strlen($columns[$i]['name']);
        }
    }

    $template_keys['phpdoc_save_summary'] .= '      * This method is used to save data to the '.$table.' table. It can be used to '."\n";
    $template_keys['phpdoc_save_summary'] .= '      * insert or update. If $'.$template_keys['id'].' is set to zero, then a new row '."\n";
    $template_keys['phpdoc_save_summary'] .= '      * will be created. The final parameter (bool $do_redirect) will determine if '."\n";
    $template_keys['phpdoc_save_summary'] .= '      * the response will be redirected to the data table for '.$table.'. ';

    foreach ($columns as $column) {

        # build save parameters
        $type = $column['type'];
        if ($type == 'timestamp') {
            $type = '\DateTime';
        }
        $template_keys['save_parameters'] .= $type.' $'.$column['name'].', ';

        # build phpdoc save parameters
        $template_keys['phpdoc_save_params'] .= '      * @param '.$type.' $'.$column['name'].' Corresponds to database column '.$table.'.'.$column['name'].".\n";

        # build save actions:
        if ($column['index'] > 0) {
            $template_keys['save_actions'] .= '        $data->'.str_pad($column['name'], $longest) .' = $'.$column['name'];

            # timestamps need a little extra formatting before saving
            if($column['type'] == 'timestamp') {
                $template_keys['save_actions'] .= '->format(\DateTime::ISO8601)';
            }
            $template_keys['save_actions'] .= ";\n";
        }

        # build form form_fields
        if ($column['index'] > 0) {
            switch ($column['type']) {
                case 'string':
                case 'int':
                case 'float':

                    if ($column['type'] == 'int' && strpos($column['name'], '_id') !== false) {
                        echo ("trying to find options for ".$column['name']."\n");
                        # this is likely a foreign key for another table. make it a select list instead of a text field
                        $source = '[]';
                        list($keyTable, $idColumn, $labelColumn) = findTableForKey($table, $column['name'], $meta);
                        if ($keyTable !== false) {
                            $source = '$'.$column['name'].'_options';
                            $template_keys['select_options'] .= '$'.$column['name'].'_options = lucid::model(\''.$keyTable.'\')';
                            $template_keys['select_options'] .= "\n    ->select('$idColumn', 'value')";
                            $template_keys['select_options'] .= "\n    ->select('$labelColumn', 'label')";
                            $template_keys['select_options'] .= "\n    ->order_by_asc('$labelColumn')";
                            $template_keys['select_options'] .= "\n    ->find_array();\n\n";
                        }

                        $template_keys['form_fields'] .= '    html::form_group(_(\'model:'.$table.':'.$column['name'].'\'), html::select(\''.$column['name'].'\', $data->'.$column['name'].', '.$source.')),'."\n";
                    } else {
                        if ($column['type'] == 'string' && is_null($template_keys['first_string_col']) === true) {
                            $template_keys['first_string_col'] = $column['name'];
                        }
                        $template_keys['form_fields'] .= '    html::form_group(_(\'model:'.$table.':'.$column['name'].'\'), html::input(\'text\', \''.$column['name'].'\', $data->'.$column['name'].')),'."\n";
                    }

                    break;
                case 'bool':
                    $template_keys['form_fields'] .= '    html::form_group(_(\'model:'.$table.':'.$column['name'].'\'), html::input(\'checkbox\', \''.$column['name'].'\', $data->'.$column['name'].')),'."\n";
                    break;
                case 'timestamp':
                    $template_keys['form_fields'] .= '    html::form_group(_(\'model:'.$table.':'.$column['name'].'\'), html::input(\'date\', \''.$column['name'].'\', (new \DateTime($data->'.$column['name'].'))->format(\'Y-m-d H:i\'))),'."\n";
                    break;
                default:
                    echo("no logic for rendering type ". $column['type']."\n");
                    break;
            }
        }

        # build the list of table columns
        if ($column['index'] > 0) {
            $template_keys['table_cols'] .= '$table->add(html::data_column(_(\'model:'.$table.':'.$column['name'].'\'), \''.$column['name'].'\', \''. ceil(90 / (count($columns) - 1)) .'%\', true));'."\n";
        }

        # build the list of searchable fields
        if ($column['index'] > 0) {
            if ($column['type'] == 'string') {
                $template_keys['search_cols'][] = "'".$column['name']."'";
            }
        }

        # build the rules
        if ($column['index'] > 0) {
            if ($column['type'] == 'string') {
                $template_keys['rules'] .= '            [\'type\'=>\'length_range\', \'label\'=>_(\'model:'.$table.':'.$column['name'].'\'), \'field\'=>\''.$column['name'].'\', \'min\'=>\'2\', \'max\'=>\'255\', ],'."\n";
            }
        }

        # build dictionaries
        $dictionary['model:'.$table.':'.$column['name']] = $column['name'];
    }
    $template_keys['search_cols'] = implode(',', $template_keys['search_cols']);

    $actions = 0;
    if ($build_model === true) {
        file_put_contents($base_dir.'/db/models/'.$table.'.php', swapTemplate('model', $template_keys));
        $actions++;
    }
    if ($build_table === true) {
        file_put_contents($base_dir.'/app/views/'.$table.'-table.php', swapTemplate('table', $template_keys));
        $actions++;
    }
    if ($build_edit === true) {
        file_put_contents($base_dir.'/app/views/'.$table.'-edit.php', swapTemplate('edit', $template_keys));
        $actions++;
    }
    if ($build_controller === true) {
        file_put_contents($base_dir.'/app/controllers/'.$table.'.php', swapTemplate('controller', $template_keys));
        $actions++;
    }
    if ($build_dictionary === true) {
        mergeDictionary($base_dir.'/dictionaries/en__models.json', $dictionary);
        $actions++;
    }

    if($actions == 0) {
        echo("WARNING: No actions performed.\n");
        printUsage();
    }
    echo("---------------------------------\n");
}

function swapTemplate($source, $keys)
{
    echo("  Building $source...\n");
    $source = file_get_contents(__DIR__.'/templates/'.$source.'.php');
    foreach ($keys as $key=>$value) {
        $source = str_replace('{{'.$key.'}}', $value, $source);
    }
    return $source;
}

function mergeDictionary(string $path, array $keys)
{
    echo("  Building dictionary...\n");
    $current = json_decode(file_get_contents($path), true);
    foreach ($keys as $key=>$value) {
        $value = ucwords(str_replace('_', ' ', $value));
        if (isset($current[$key]) === false) {
            $current[$key] = $value;
        }
    }
    ksort($current);
    file_put_contents($path, json_encode($current, JSON_PRETTY_PRINT));
}

function printUsage()
{
    echo("\nUsage: scripts/build table_name|all [model=[tf]|table=[tf]|edit=[tf]|controller=[tf]|dictionary=[tf]]\n\n");
    echo("Ex: scripts/build users\n");
    echo("Ex: scripts/build users model=t table=f\n");
    echo("Ex: scripts/build all model=f table=f edit=f controller=f dictionary=t\n");
    exit("\n");
}

function findTableForKey($table, $key, $meta)
{
    $tables = $meta->getTables(false);

    for ($i=0; $i<count($tables); $i++) {
        $tableCols = $meta->getColumns($tables[$i]);
        if ($tableCols[0]['name'] == $key) {
            $return = [
                $tables[$i],
                $tableCols[0]['name'],
            ];

            for ($j = 1; $j<count($tableCols); $j++) {
                if ($tableCols[$j]['type'] == 'string'){
                    $return[] = $tableCols[$j]['name'];
                    return $return;
                }

            }
            lucid::log('Could not find a label column in table '.$tables[$i].'. Build script looks for the first column that is of a string type (varchar, char, text, etc).');
            return [false, false, false];
        }
    }

    lucid::log('Could not find a table to use as a source for '.$key.' select.');
    return [false, false, false];
}
