#!/usr/bin/php
<?php
include(__DIR__.'/../../../../bootstrap.php');

array_shift($argv);
$action = array_shift($argv);

switch ($action) {
    case 'db-status':
        wrap_phinx_command('status', $argv, true);
        break;
    case 'db-create':
        wrap_phinx_command('create', $argv, false);
        break;
    case 'db-migrate':
        wrap_phinx_command('migrate', $argv, true );
        break;
    case 'db-rollback':
        wrap_phinx_command('rollback', $argv, true);
        break;
    default:
        echo("Unknown action. Supported actions are: db-status, db-create, db-migrate, db-rollback\n");
        exit();
        break;
}

function wrap_phinx_command($command, $params, $include_stage = true)
{
    $cmd = 'scripts/phinx '.$command.' '.implode(' ',$params).' --configuration vendor/devlucid/lucid/config/phinx.php';

    if ($include_stage === true) {
        $cmd .= ' -e '.lucid::$stage;
    }


    try {
        echo(shell_exec($cmd));
    } catch(Exception $e) {
        exit($e->getMessage()."\n");
    }
}

